name: flutter_app_icon_badge
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8
dependencies:
  flutter:
    sdk: flutter
  
  #== Core Architecture: 상태관리, 라우팅, 의존성 주입 ==#
  flutter_bloc: ^9.1.1
  go_router: ^17.0.1
  get_it: ^9.2.0
  injectable: ^2.7.1+4

  #== Networking & API: HTTP 통신, API 클라이언트, 데이터 모델 ==#
  dio: ^5.9.0
  retrofit: ^4.9.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  equatable: ^2.0.8

  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  app_badge_plus: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  #== Code Generation: 코드 자동 생성을 위한 도구들 ==#
  build_runner: ^2.10.5
  injectable_generator: ^2.12.0
  retrofit_generator: ^10.2.1
  freezed: ^3.2.4
  json_serializable: ^6.11.4

flutter:

  uses-material-design: true